### Variables
@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6IkVkdWFyZG8gNDY1IiwiZW1haWwiOiJoaWFzZDEyZUBnbWFpbC5jb20iLCJyb2wiOiJBZG1pbmlzdHJhZG9yIiwiYWN0aXZvIjoxLCJpYXQiOjE3NzY0MjM2MzIsImV4cCI6MTc3OTAxNTYzMn0.SKnwwkGf_PvO8tQDssG32D9zLkRPoDRvbUIgZHmJKdM
@usuario_id = 8

### ─── PERFILES ───────────────────────────────────────────

### Obtener todos los perfiles
GET {{baseUrl}}/usuarios/perfiles
Authorization: Bearer {{token}}

### Obtener perfil por usuario_id
GET {{baseUrl}}/usuarios/perfiles/{{usuario_id}}
Authorization: Bearer {{token}}

### Crear perfil para un usuario
POST {{baseUrl}}/usuarios/perfiles/{{usuario_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Juan2",
    "apellido": "Pérez2",
    "edad": 252,
    "telefono": "55123456782"
}

### Actualizar perfil de un usuario
PUT {{baseUrl}}/usuarios/perfiles/{{usuario_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "González",
    "edad": 26,
    "telefono": "5598765432"
}

### Eliminar perfil de un usuario
DELETE {{baseUrl}}/usuarios/perfiles/{{usuario_id}}
Authorization: Bearer {{token}}